trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
# Development Stage
- stage: Dev
  jobs:
  - job: DeployToDev
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Azure subscription 1(41a8d72c-b0d9-45ef-b78c-12163a697ed0)'
        appType: 'webAppLinux'
        appName: 'assets-manager-api-dev'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'

# Production Stage with Approval
- stage: Prod
  dependsOn: Dev
  condition: succeeded()
  jobs:
  - deployment: DeployToProd
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'Azure subscription 1(41a8d72c-b0d9-45ef-b78c-12163a697ed0)'
              appType: 'webAppLinux'
              appName: 'assets-manager-api'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
